// Code generated by gendict. DO NOT EDIT.

package audience

import "github.com/rtb-0/rtbdict/iab/dict"

var taxonomies []*dict.Taxonomy

func register(t *dict.Taxonomy) {
	taxonomies = append(taxonomies, t)
}

// ByID returns the taxonomy with meta.id.
func ByID(id string) (*dict.Taxonomy, bool) {
	for _, t := range taxonomies {
		if t.Meta.ID == id {
			return t, true
		}
	}
	return nil, false
}

// ByCattax returns the taxonomy whose cattax is set to cattax.
func ByCattax(cattax int) (*dict.Taxonomy, bool) {
	if cattax == 0 {
		return nil, false
	}
	var found *dict.Taxonomy
	for _, t := range taxonomies {
		if t.Meta.Cattax != cattax {
			continue
		}
		if found != nil {
			return nil, false
		}
		found = t
	}
	if found == nil {
		return nil, false
	}
	return found, true
}
