// Code generated by genlight. DO NOT EDIT.

package content

import "github.com/rtb-0/rtbdict/iab/lightdict"

// ByID returns the taxonomy with this id. An unknown id returns nil.
func ByID(id string) *lightdict.Taxonomy {
	switch id {
	case "iab.content.1.0":
		return v10
	case "iab.content.2.0":
		return v20
	case "iab.content.2.1":
		return v21
	case "iab.content.2.2":
		return v22
	case "iab.content.3.0":
		return v30
	case "iab.content.3.0-vectors":
		return v30Vectors
	case "iab.content.3.1":
		return v31
	default:
		return nil
	}
}

// ByCattax returns the taxonomy whose cattax is set to cattax. An unknown cattax returns nil.
func ByCattax(cattax int) *lightdict.Taxonomy {
	switch cattax {
	case 1:
		return v10
	case 2:
		return v20
	case 5:
		return v21
	case 6:
		return v22
	case 7:
		return v30
	case 9:
		return v31
	default:
		return nil
	}
}
