// Code generated by genlight. DO NOT EDIT.

package mappings

import "github.com/rtb-0/rtbdict/iab/lightdict"

// ByID returns the mapping with this id. An unknown id returns nil.
func ByID(id string) *lightdict.Mapping {
	switch id {
	case "iab.map.ad-product-2.0.ad-product-1.1":
		return vAdProduct20ToAdProduct11
	case "iab.map.ad-product-2.0.content-1.0":
		return vAdProduct20ToContent10
	case "iab.map.ad-product-2.0.content-2.1":
		return vAdProduct20ToContent21
	case "iab.map.content-1.0.ad-product-2.0":
		return vContent10ToAdProduct20
	case "iab.map.content-1.0.content-2.0":
		return vContent10ToContent20
	case "iab.map.content-1.0.content-2.1":
		return vContent20ToContent21
	case "iab.map.content-2.1.ad-product-2.0":
		return vContent21ToAdProduct20
	case "iab.map.ctv-genre.content-3.1":
		return vCtvGenreToContent31
	case "iab.map.podcast-genre.content-3.1":
		return vPodcastGenreToContent31
	default:
		return nil
	}
}

// ByTaxonomy returns the mapping from one taxonomy id to another.
// An unknown pair, or a pair shared by more than one mapping, returns nil.
func ByTaxonomy(fromID, toID string) *lightdict.Mapping {
	switch fromID {
	case "iab.ad-product.2.0":
		switch toID {
		case "iab.ad-product.1.1":
			return vAdProduct20ToAdProduct11
		case "iab.content.1.0":
			return vAdProduct20ToContent10
		case "iab.content.2.1":
			return vAdProduct20ToContent21
		}
	case "iab.content.1.0":
		switch toID {
		case "iab.ad-product.2.0":
			return vContent10ToAdProduct20
		case "iab.content.2.0":
			return vContent10ToContent20
		case "iab.content.2.1":
			return vContent20ToContent21
		}
	case "iab.content.2.1":
		switch toID {
		case "iab.ad-product.2.0":
			return vContent21ToAdProduct20
		}
	}
	return nil
}
