// Code generated by gendict. DO NOT EDIT.

package mappings

import "github.com/rtb-0/rtbdict/iab/dict"

func init() {
	register(dict.NewMapping(dict.Meta{ID: "iab.map.ctv-genre.content-3.1", Kind: "mapping", Name: "CTV Genre to Content 3.1", Publisher: "IAB Tech Lab", Page: "https://iabtechlab.com/standards/content-taxonomy/", Source: "https://github.com/InteractiveAdvertisingBureau/Taxonomies/blob/main/Taxonomy%20Mappings/CTV%20Genre%20Mapping.tsv", Released: "2024-12", To: "iab.content.3.1", ToCattax: 9}, []dict.Entry{
		{From: dict.Ref{Name: "Action"}, To: &dict.Ref{ID: "325", Name: "Action/Adventure"}},
		{From: dict.Ref{Name: "Adventure"}, To: &dict.Ref{ID: "325", Name: "Action/Adventure"}},
		{From: dict.Ref{Name: "Animals"}, To: &dict.Ref{ID: "422", Name: "Pets"}},
		{From: dict.Ref{Name: "Animation"}, To: &dict.Ref{ID: "641", Name: "Animation & Anime"}},
		{From: dict.Ref{Name: "Anime"}, To: &dict.Ref{ID: "641", Name: "Animation & Anime"}},
		{From: dict.Ref{Name: "Arts"}, To: &dict.Ref{ID: "201", Name: "Fine Art"}},
		{From: dict.Ref{Name: "Automotive"}, To: &dict.Ref{ID: "1", Name: "Automotive"}},
		{From: dict.Ref{Name: "Awards"}, To: &dict.Ref{ID: "162", Name: "Awards Shows"}},
		{From: dict.Ref{Name: "Biography"}, To: &dict.Ref{ID: "44", Name: "Biographies"}},
		{From: dict.Ref{Name: "Business & Finance"}, To: &dict.Ref{ID: "52", Name: "Business and Finance"}},
		{From: dict.Ref{Name: "Children"}, To: &dict.Ref{ID: "645", Name: "Family/Children"}},
		{From: dict.Ref{Name: "Comedy"}, To: &dict.Ref{ID: "646", Name: "Comedy"}},
		{From: dict.Ref{Name: "Cooking"}, To: &dict.Ref{ID: "216", Name: "Cooking"}},
		{From: dict.Ref{Name: "Crime"}, To: &dict.Ref{ID: "KHPC5A", Name: "True Crime"}},
		{From: dict.Ref{Name: "Documentary"}, To: &dict.Ref{ID: "332", Name: "Documentary"}},
		{From: dict.Ref{Name: "Drama"}, To: &dict.Ref{ID: "647", Name: "Drama"}},
		{From: dict.Ref{Name: "Education"}, To: &dict.Ref{ID: "132", Name: "Education"}},
		{From: dict.Ref{Name: "Family"}, To: &dict.Ref{ID: "645", Name: "Family/Children"}},
		{From: dict.Ref{Name: "Fantasy"}, To: &dict.Ref{ID: "335", Name: "Fantasy"}},
		{From: dict.Ref{Name: "Game Show"}, To: &dict.Ref{ID: "JLBCU7", Name: "Entertainment"}},
		{From: dict.Ref{Name: "Gaming"}, To: &dict.Ref{ID: "680", Name: "Video Gaming"}},
		{From: dict.Ref{Name: "History"}, To: &dict.Ref{ID: "EZWB7V", Name: "History"}},
		{From: dict.Ref{Name: "Hobbies"}, To: &dict.Ref{ID: "239", Name: "Hobbies & Interests"}},
		{From: dict.Ref{Name: "Holidays"}, To: &dict.Ref{ID: "649", Name: "Holiday"}},
		{From: dict.Ref{Name: "Home & Garden"}, To: &dict.Ref{ID: "274", Name: "Home & Garden"}},
		{From: dict.Ref{Name: "Horror"}, To: &dict.Ref{ID: "336", Name: "Horror"}},
		{From: dict.Ref{Name: "Law"}, To: &dict.Ref{ID: "383", Name: "Law"}},
		{From: dict.Ref{Name: "Mystery"}, To: &dict.Ref{ID: "331", Name: "Mystery"}},
		{From: dict.Ref{Name: "News"}, To: &dict.Ref{ID: "1020", Name: "News"}},
		{From: dict.Ref{Name: "Outdoors"}, To: &dict.Ref{ID: "159", Name: "Outdoor Activities"}},
		{From: dict.Ref{Name: "Paranormal"}, To: &dict.Ref{ID: "244", Name: "Parnormal Phenomenons"}},
		{From: dict.Ref{Name: "Politics"}, To: &dict.Ref{ID: "386", Name: "Politics"}},
		{From: dict.Ref{Name: "Reality"}, To: &dict.Ref{ID: "651", Name: "Reality TV"}},
		{From: dict.Ref{Name: "Religion"}, To: &dict.Ref{ID: "453", Name: "Religion & Spirituality"}},
		{From: dict.Ref{Name: "Romance"}, To: &dict.Ref{ID: "326", Name: "Romance"}},
		{From: dict.Ref{Name: "Sci-Fi"}, To: &dict.Ref{ID: "652", Name: "Science Fiction"}},
		{From: dict.Ref{Name: "Sitcom"}, To: &dict.Ref{ID: "646", Name: "Comedy"}},
		{From: dict.Ref{Name: "Soap-Opera"}, To: &dict.Ref{ID: "642", Name: "Soap Opera"}},
		{From: dict.Ref{Name: "Sports"}, To: &dict.Ref{ID: "483", Name: "Sports"}},
		{From: dict.Ref{Name: "Thriller"}, To: &dict.Ref{ID: "700", Name: "Thriller"}},
		{From: dict.Ref{Name: "War"}, To: &dict.Ref{ID: "389", Name: "War and Conflicts"}},
		{From: dict.Ref{Name: "Weather"}, To: &dict.Ref{ID: "390", Name: "Weather"}},
		{From: dict.Ref{Name: "Western"}, To: &dict.Ref{ID: "KHPC6A", Name: "Western"}},
		{From: dict.Ref{Name: "Young Adult"}, To: &dict.Ref{ID: "51", Name: "Young Adult"}},
	}))
}
