// Code generated by gendict. DO NOT EDIT.

package mappings

import "github.com/rtb-0/rtbdict/iab/dict"

var mappings []*dict.Mapping

func register(m *dict.Mapping) {
	mappings = append(mappings, m)
}

// ByID returns the mapping with meta.id.
func ByID(id string) (*dict.Mapping, bool) {
	for _, m := range mappings {
		if m.Meta.ID == id {
			return m, true
		}
	}
	return nil, false
}

// ByTaxonomy returns the mapping from one taxonomy id to another.
func ByTaxonomy(fromID, toID string) (*dict.Mapping, bool) {
	var found *dict.Mapping
	for _, m := range mappings {
		if m.Meta.From != fromID || m.Meta.To != toID {
			continue
		}
		if found != nil {
			return nil, false
		}
		found = m
	}
	if found == nil {
		return nil, false
	}
	return found, true
}
