// Code generated by genlight. DO NOT EDIT.

package audience

import "github.com/rtb-0/rtbdict/iab/lightdict"

// ByID returns the taxonomy with this id. An unknown id returns nil.
func ByID(id string) *lightdict.Taxonomy {
	switch id {
	case "iab.audience.1.0":
		return v10
	case "iab.audience.1.1":
		return v11
	default:
		return nil
	}
}

// ByCattax returns the taxonomy whose cattax is set to cattax. An unknown cattax returns nil.
func ByCattax(cattax int) *lightdict.Taxonomy {
	switch cattax {
	case 0:
		return v10
	case 4:
		return v11
	default:
		return nil
	}
}
