package main

import (
	"bytes"
	"fmt"
	"sort"
	"strconv"
)

type kwBuild struct {
	id        int
	phraseLen int
	children  map[byte]*kwBuild
}

type kwNode struct {
	id        int
	phraseLen uint16
	edgeOff   uint32
	edgeCount uint16
}

type kwEdge struct {
	b     byte
	child uint32
}

func keywordTrie(categories []node) ([]kwNode, []kwEdge) {
	root := &kwBuild{children: map[byte]*kwBuild{}}
	for _, n := range categories {
		seen := map[string]bool{}
		addPhrase(root, n.name, n.id, seen)
		for _, phrase := range n.keywords {
			addPhrase(root, phrase, n.id, seen)
		}
	}
	var nodes []kwNode
	var edges []kwEdge
	nodes = append(nodes, kwNode{})
	freezeKeyword(root, 0, &nodes, &edges)
	return nodes, edges
}

func addPhrase(root *kwBuild, phrase string, id int, seen map[string]bool) {
	norm := normalizePhrase(phrase)
	if norm == "" || id == 0 || seen[norm] {
		return
	}
	seen[norm] = true
	n := root
	for i := 0; i < len(norm); i++ {
		b := norm[i]
		child := n.children[b]
		if child == nil {
			child = &kwBuild{children: map[byte]*kwBuild{}}
			n.children[b] = child
		}
		n = child
	}
	if n.phraseLen == 0 || id > n.id {
		n.id = id
		n.phraseLen = len(norm)
	}
}

func normalizePhrase(s string) string {
	buf := make([]byte, 0, len(s))
	space := false
	started := false
	for i := 0; i < len(s); i++ {
		c := s[i]
		if c >= 'A' && c <= 'Z' {
			c += 'a' - 'A'
		}
		if c == ' ' || c == '\t' || c == '\n' || c == '\r' || c == '\f' || c == '\v' {
			if started {
				space = true
			}
			continue
		}
		if space {
			buf = append(buf, ' ')
			space = false
		}
		buf = append(buf, c)
		started = true
	}
	return string(buf)
}

func freezeKeyword(bn *kwBuild, idx uint32, nodes *[]kwNode, edges *[]kwEdge) {
	n := &(*nodes)[idx]
	n.id = bn.id
	if bn.phraseLen > 0 {
		if bn.phraseLen > 0xffff {
			panic("keyword phrase too long")
		}
		n.phraseLen = uint16(bn.phraseLen)
	}
	if len(bn.children) == 0 {
		return
	}
	keys := make([]byte, 0, len(bn.children))
	for b := range bn.children {
		keys = append(keys, b)
	}
	sort.Slice(keys, func(i, j int) bool { return keys[i] < keys[j] })
	if len(keys) > 0xffff {
		panic("keyword fanout too wide")
	}
	n.edgeOff = uint32(len(*edges))
	n.edgeCount = uint16(len(keys))
	base := len(*edges)
	for range keys {
		*edges = append(*edges, kwEdge{})
	}
	for i, b := range keys {
		childIdx := uint32(len(*nodes))
		*nodes = append(*nodes, kwNode{})
		(*edges)[base+i] = kwEdge{b: b, child: childIdx}
		freezeKeyword(bn.children[b], childIdx, nodes, edges)
	}
}

func renderKeyword(nodes []kwNode, edges []kwEdge) []byte {
	var b bytes.Buffer
	b.WriteString("// Code generated by r0/cmd/gendict. DO NOT EDIT.\n\n")
	b.WriteString("package keyword\n\n")
	b.WriteString("var nodes = []node{\n")
	for _, n := range nodes {
		fmt.Fprintf(&b, "\t{id: %d, phraseLen: %d, edgeOff: %d, edgeCount: %d},\n", n.id, n.phraseLen, n.edgeOff, n.edgeCount)
	}
	b.WriteString("}\n\nvar edges = []edge{\n")
	for _, e := range edges {
		fmt.Fprintf(&b, "\t{b: %s, child: %d},\n", strconv.QuoteRune(rune(e.b)), e.child)
	}
	b.WriteString("}\n")
	return b.Bytes()
}
