// Command gendict writes the r0 content dictionaries from r0/datasets/content/1.0.json.
package main

import (
	"bytes"
	"encoding/json"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"sort"
	"strconv"
)

func main() {
	root, err := moduleRoot()
	if err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
	nodes, err := build(root)
	if err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
	byR0, byCattax, err := indexes(nodes)
	if err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
	kwNodes, kwEdges := keywordTrie(nodes)
	if err := writeGo(filepath.Join(root, "r0", "keyword", "content", "phrases.go"), renderKeyword(kwNodes, kwEdges)); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
	for _, out := range []struct {
		dir  string
		desc bool
	}{
		{"dict", true},
		{"lightdict", false},
	} {
		src := render(out.desc, nodes, byR0, byCattax)
		path := filepath.Join(root, "r0", out.dir, "content", "1.0.go")
		if err := writeGo(path, src); err != nil {
			fmt.Fprintln(os.Stderr, err)
			os.Exit(1)
		}
	}
}

func moduleRoot() (string, error) {
	dir, err := os.Getwd()
	if err != nil {
		return "", err
	}
	for {
		if _, err := os.Stat(filepath.Join(dir, "go.mod")); err == nil {
			return dir, nil
		}
		parent := filepath.Dir(dir)
		if parent == dir {
			return "", fmt.Errorf("go.mod not found")
		}
		dir = parent
	}
}

type rawIAB struct {
	Cattax int    `json:"cattax"`
	ID     string `json:"id"`
	Name   string `json:"name"`
}

type rawNode struct {
	ID          int       `json:"id"`
	R0Code      string    `json:"r0_code"`
	Name        string    `json:"name"`
	Description string    `json:"description"`
	Keywords    []string  `json:"keywords"`
	Position    int       `json:"position"`
	IAB         []rawIAB  `json:"iab"`
	Children    []rawNode `json:"children"`
}

type node struct {
	id                        int
	r0Code, name, description string
	keywords                  []string
	position, parent          int
	children                  []int
	iab                       []rawIAB
}

func build(root string) ([]node, error) {
	body, err := os.ReadFile(filepath.Join(root, "r0", "datasets", "content", "1.0.json"))
	if err != nil {
		return nil, err
	}
	var doc struct {
		Nodes []rawNode `json:"nodes"`
	}
	if err := json.Unmarshal(body, &doc); err != nil {
		return nil, err
	}
	var nodes []node
	var walk func([]rawNode, int) error
	walk = func(raw []rawNode, parent int) error {
		for _, r := range raw {
			if r.R0Code == "" {
				return fmt.Errorf("node %d missing r0_code", r.ID)
			}
			n := node{
				id: r.ID, r0Code: r.R0Code, name: r.Name, description: r.Description,
				keywords: r.Keywords, position: r.Position, parent: parent,
				iab: append([]rawIAB(nil), r.IAB...),
			}
			for _, code := range n.iab {
				if code.Cattax <= 0 || code.ID == "" || code.Name == "" {
					return fmt.Errorf("node %s has an incomplete iab entry", n.r0Code)
				}
			}
			for _, child := range r.Children {
				n.children = append(n.children, child.ID)
			}
			nodes = append(nodes, n)
			if err := walk(r.Children, r.ID); err != nil {
				return err
			}
		}
		return nil
	}
	if err := walk(doc.Nodes, 0); err != nil {
		return nil, err
	}
	sort.Slice(nodes, func(i, j int) bool { return nodes[i].id < nodes[j].id })
	for i, n := range nodes {
		if n.id != i+1 {
			return nil, fmt.Errorf("r0 id gap at %d", i+1)
		}
	}
	return nodes, nil
}

func indexes(nodes []node) (map[string]int, [10]map[string]int, error) {
	byR0 := make(map[string]int, len(nodes))
	var byCattax [10]map[string]int
	for i := range byCattax {
		byCattax[i] = map[string]int{}
	}
	for _, n := range nodes {
		if _, ok := byR0[n.r0Code]; ok {
			return nil, byCattax, fmt.Errorf("duplicate r0_code %s", n.r0Code)
		}
		byR0[n.r0Code] = n.id
		for _, code := range n.iab {
			if code.Cattax >= len(byCattax) {
				return nil, byCattax, fmt.Errorf("cattax %d on %s is out of range", code.Cattax, n.r0Code)
			}
			if prev, ok := byCattax[code.Cattax][code.ID]; ok {
				return nil, byCattax, fmt.Errorf("duplicate cattax %d id %s on nodes %d and %d", code.Cattax, code.ID, prev, n.id)
			}
			byCattax[code.Cattax][code.ID] = n.id
		}
	}
	return byR0, byCattax, nil
}

func render(withDescription bool, nodes []node, byR0 map[string]int, byCattax [10]map[string]int) []byte {
	var b bytes.Buffer
	b.WriteString("// Code generated by r0/cmd/gendict. DO NOT EDIT.\n\n")
	b.WriteString("package content\n\n")
	b.WriteString("var nodes = []Node{\n")
	for _, n := range nodes {
		fmt.Fprintf(&b, "\t{id: %d, r0Code: %s, name: %s", n.id, strconv.Quote(n.r0Code), strconv.Quote(n.name))
		if withDescription && n.description != "" {
			fmt.Fprintf(&b, ", description: %s", strconv.Quote(n.description))
		}
		writeStrings(&b, "keywords", n.keywords)
		if n.position != 0 {
			fmt.Fprintf(&b, ", position: %d", n.position)
		}
		writeIAB(&b, n.iab, withDescription)
		if n.parent != 0 {
			fmt.Fprintf(&b, ", parent: %d", n.parent)
		}
		if len(n.children) > 0 {
			b.WriteString(", children: []int{")
			for i, id := range n.children {
				if i > 0 {
					b.WriteString(", ")
				}
				b.WriteString(strconv.Itoa(id))
			}
			b.WriteString("}")
		}
		b.WriteString("},\n")
	}
	b.WriteString("}\n\n")
	writeMap(&b, "var byR0 = map[string]int{\n", byR0)
	b.WriteString("\nvar byCattax = [10]map[string]int{\n")
	for cattax, codes := range byCattax {
		if len(codes) == 0 {
			continue
		}
		fmt.Fprintf(&b, "\t%d: map[string]int{\n", cattax)
		keys := make([]string, 0, len(codes))
		for code := range codes {
			keys = append(keys, code)
		}
		sort.Strings(keys)
		for _, code := range keys {
			fmt.Fprintf(&b, "\t\t%s: %d,\n", strconv.Quote(code), codes[code])
		}
		b.WriteString("\t},\n")
	}
	b.WriteString("}\n")
	return b.Bytes()
}

func writeIAB(b *bytes.Buffer, items []rawIAB, withName bool) {
	if len(items) == 0 {
		return
	}
	b.WriteString(", iab: []IAB{")
	for i, item := range items {
		if i > 0 {
			b.WriteString(", ")
		}
		if withName {
			fmt.Fprintf(b, "{Cattax: %d, ID: %s, Name: %s}", item.Cattax, strconv.Quote(item.ID), strconv.Quote(item.Name))
			continue
		}
		fmt.Fprintf(b, "{Cattax: %d, ID: %s}", item.Cattax, strconv.Quote(item.ID))
	}
	b.WriteString("}")
	writeIABIDs(b, items)
}

func writeIABIDs(b *bytes.Buffer, items []rawIAB) {
	var grouped [10][]string
	for _, item := range items {
		grouped[item.Cattax] = append(grouped[item.Cattax], item.ID)
	}
	b.WriteString(", ids: [10][]string{")
	for cattax, ids := range grouped {
		if len(ids) == 0 {
			continue
		}
		fmt.Fprintf(b, "%d: []string{", cattax)
		for i, id := range ids {
			if i > 0 {
				b.WriteString(", ")
			}
			b.WriteString(strconv.Quote(id))
		}
		b.WriteString("}, ")
	}
	b.WriteString("}")
}

func writeStrings(b *bytes.Buffer, name string, values []string) {
	if len(values) == 0 {
		return
	}
	fmt.Fprintf(b, ", %s: []string{", name)
	for i, v := range values {
		if i > 0 {
			b.WriteString(", ")
		}
		b.WriteString(strconv.Quote(v))
	}
	b.WriteString("}")
}

func writeMap(b *bytes.Buffer, header string, values map[string]int) {
	b.WriteString(header)
	keys := make([]string, 0, len(values))
	for key := range values {
		keys = append(keys, key)
	}
	sort.Strings(keys)
	for _, key := range keys {
		fmt.Fprintf(b, "\t%s: %d,\n", strconv.Quote(key), values[key])
	}
	b.WriteString("}\n")
}

func writeGo(path string, src []byte) error {
	formatted, err := format.Source(src)
	if err != nil {
		return fmt.Errorf("format %s: %w", path, err)
	}
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return err
	}
	return os.WriteFile(path, formatted, 0o644)
}
