// Code generated by genlight. DO NOT EDIT.

package adproduct

import "github.com/rtb-0/rtbdict/iab/lightdict"

// ByID returns the taxonomy with this id. An unknown id returns nil.
func ByID(id string) *lightdict.Taxonomy {
	switch id {
	case "iab.ad-product.1.0":
		return v10
	case "iab.ad-product.1.1":
		return v11
	case "iab.ad-product.2.0":
		return v20
	default:
		return nil
	}
}

// ByCattax returns the taxonomy whose cattax is set to cattax. An unknown cattax returns nil.
func ByCattax(cattax int) *lightdict.Taxonomy {
	switch cattax {
	case 3:
		return v10
	case 8:
		return v20
	default:
		return nil
	}
}
